name: Pull Request Validator
on:
  pull_request:
    paths:
      - "triggers/**"
    branches: [main]
jobs:
  pull-request-validator:
    name: Validator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            cwd: util
      - uses: actions/github-script@v6
        with:
          script: |
            const validate = require("./util/pull-request-validator.js");
            await validate({ github, context, core });
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: validation-results.json
          path: validation-results.json
          retention-days: 1
